#!/bin/sh

xsetroot -cursor_name left_ptr &

## Bspwm configurations
bspc monitor -d 'main' 'www' 'irc' 'mail' 'foo' 'bar'
bspc config focus_follows_pointer   true
bspc config initial_polarity        second_child
bspc config border_width            2
bspc config window_gap              7
bspc config normal_border_color     "#444444"
bspc config focused_border_color    "#FFFFFF"
bspc config presel_feedback_color   "#2c3939"
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config border_radius 	    1
bspc config split_ratio             0.5
bspc config bottom_padding          35
bspc config left_padding            10
bspc config right_padding           10
bspc config top_padding             10
